apiVersion: v1
kind: Service
metadata:
  name: apexpos-backend-svc
  namespace: apexpos
spec:
  type: NodePort
  selector:
    app: apexpos-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
