FROM jenkins/jenkins:lts
USER root
# Install docker.io and curl (needed to get kubectl)
RUN apt-get update && \
    apt-get install -y --no-install-recommends docker.io curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*
# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl
