apiVersion: apps/v1
kind: Deployment
metadata:
  name: apexpos-frontend
  namespace: apexpos
  labels:
    app: apexpos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apexpos-frontend
  template:
    metadata:
      labels:
        app: apexpos-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/ntharusha/apexpos-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
