{{- if .Values.database.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apexpos.fullname" . }}-database-pvc
  labels:
    {{- include "apexpos.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.database.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  {{- if .Values.database.persistence.storageClass }}
  storageClassName: {{ .Values.database.persistence.storageClass | quote }}
  {{- end }}
{{- end -}}
