apiVersion: v1
kind: Service
metadata:
  name: {{ include "apexpos.fullname" . }}-database
  labels:
    {{- include "apexpos.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "apexpos.selectorLabels" . | nindent 4 }}
    app: {{ include "apexpos.fullname" . }}-database
  type: ClusterIP
