apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apexpos.fullname" . }}-backend-secrets
  labels:
    {{- include "apexpos.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | quote }}
