apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apexpos-ingress
  namespace: apexpos
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Route traffic for backend API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apexpos-backend-svc
                port:
                  number: 5000
          # Route all other traffic to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apexpos-frontend-svc
                port:
                  number: 80
